### ISSUE TITLE
ERROR- !!! Exception during processing!!! detect_language can only be called on multilingual models

### ISSUE THREAD

**Issue by hyongqi** [AIFSH/ComfyUI-WhisperX#1]
插件运行出错
2024-04-26 14:31:55,473- root:179- ERROR- !!! Exception during processing!!! detect_language can only be called on multilingual models
2024-04-26 14:31:55,474- root:180- ERROR- Traceback (most recent call last):
  File "D:\tools\ComfyUI-aki-v1.3\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\tools\ComfyUI-aki-v1.3\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\tools\ComfyUI-aki-v1.3\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-WhisperX\nodes.py", line 89, in get_srt
    result = model.transcribe(audio, batch_size=batch_size)
  File "D:\tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-WhisperX\whisperx\asr.py", line 194, in transcribe
    language = language or self.detect_language(audio)
  File "D:\tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-WhisperX\whisperx\asr.py", line 253, in detect_language
    results = self.model.model.detect_language(encoder_output)
RuntimeError: detect_language can only be called on multilingual models

**Comment by AIFSH** [comment]
readme，make sure huggingface is attached

**Comment by AIFSH** [comment]
readme，make sure huggingface is attached
