### ISSUE TITLE
error！！！！

### ISSUE THREAD

**Issue by hyongqi** [AIFSH/ComfyUI-WhisperX#2]
1、The following error occurs when using large-v2 for model_type：
--------------------------------------------------------------------------------------------------------------
2024-04-27 13:55:19,387- root:179- ERROR- !!! Exception during processing!!! local variable 'diarize_model' referenced before assignment
2024-04-27 13:55:19,388- root:180- ERROR- Traceback (most recent call last):
  File "D:\tools\ComfyUI-aki-v1.3\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\tools\ComfyUI-aki-v1.3\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\tools\ComfyUI-aki-v1.3\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-WhisperX\nodes.py", line 136, in get_srt
    import gc; gc.collect(); torch.cuda.empty_cache(); del diarize_model
UnboundLocalError: local variable 'diarize_model' referenced before assignment

2、The following error occurs when using large-v3 for model_type：
--------------------------------------------------------------------------------------------------------------
2024-04-27 14:01:37,423- root:179- ERROR- !!! Exception during processing!!! detect_language can only be called on multilingual models
2024-04-27 14:01:37,423- root:180- ERROR- Traceback (most recent call last):
  File "D:\tools\ComfyUI-aki-v1.3\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\tools\ComfyUI-aki-v1.3\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\tools\ComfyUI-aki-v1.3\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-WhisperX\nodes.py", line 89, in get_srt
    result = model.transcribe(audio, batch_size=batch_size)
  File "D:\tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-WhisperX\whisperx\asr.py", line 194, in transcribe
    language = language or self.detect_language(audio)
  File "D:\tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-WhisperX\whisperx\asr.py", line 253, in detect_language
    results = self.model.model.detect_language(encoder_output)
RuntimeError: detect_language can only be called on multilingual models

**Comment by hyongqi** [comment]
Note: large-v2 and large-v3 Models have been downloaded

**Comment by AIFSH** [comment]
> Note: large-v2 and large-v3 Models have been downloaded

make sure large-v2 or v3 download complete
